@startuml Hotel Management System

left to right direction

skinparam usecase {
    BackgroundColor peachpuff
    BorderColor black
}

skinparam actor {
    Style stickman
}

rectangle "System Boundary" {
    usecase "Register" as register
    ' usecase "Login" as login
    ' usecase "Logout" as logout
    ' usecase "View\nProfile" as viewProfile
    
    usecase "Manage\nHotels" as manageHotels
    usecase "View\nHotels" as viewHotels
    
    usecase "Manage \nBookings" as manageBookings
}

actor User
actor Admin

' User relationships
User -- register
' User -- login
' User -- logout 
User -- viewHotels
User -- manageBookings
' User -- viewProfile

' Admin relationshipsUser -- viewProfile : access
register -- Admin
' login -- Admin
' logout -- Admin
manageBookings -- Admin
manageHotels -- Admin
' viewProfile -- Admin

' Position Admin to the right
@enduml